const assert = require('node:assert/strict');
const fs = require('node:fs');
const Module = require('node:module');
const path = require('node:path');
const tags = require('../lib/case-tags');
assert.deepEqual(tags.normalize(' 변기막힘 / 서울변기막힘, #변기막힘 / '), ['변기막힘','서울변기막힘']);
assert.deepEqual(tags.normalize(undefined), []);
const ten = Array.from({length:10},(_,i)=>`태그${i}`);
assert.deepEqual(tags.normalize(ten.join('/')),ten);
assert.throws(()=>tags.normalize([...ten,'초과']),/최대 10개/);
assert.equal(tags.render(undefined),'');
assert.ok(!tags.render(['<script>']).includes('<script>'));
const file = path.resolve(__dirname,'../api/admin.js');
const mod = new Module(file,module); mod.filename=file;mod.paths=module.paths;
mod._compile(fs.readFileSync(file,'utf8')+'\nmodule.exports={normalize,article,makeIdentity};',file);
const api=mod.exports;
const cases=require('../content/admin-cases.json');
const before=JSON.stringify(cases);
for(const c of cases) {
  const normalized=api.normalize({...c,originalPath:c.path},cases);
  assert.deepEqual(normalized.tags,[]);
  assert.equal(api.article(normalized).includes('class="case-tags"'),false);
}
const original=cases[0];
const tagged={...original,tags:ten};
assert.deepEqual(api.normalize({...original,originalPath:original.path},[tagged]).tags,ten);
assert.deepEqual(api.normalize({...original,originalPath:original.path,tags:[]},[tagged]).tags,[]);
const next=api.normalize({...original,tags:ten.join(' / ')} ,cases);
const identity=api.makeIdentity(next,cases);
assert.ok(!cases.some(c=>c.path===identity.path));
next.path=identity.path;
const html=api.article(next);
assert.equal((html.match(/class="case-tag"/g)||[]).length,10);
assert.ok(html.indexOf('class="case-tags"')>html.lastIndexOf('1877-0558 전화상담'));
assert.ok(html.indexOf('class="case-tags"')>html.indexOf('<iframe'));
const clean=api.article({...next,tags:[]});
assert.equal(html.replace(tags.render(ten),''),clean,'tags must not alter SEO/body/images');
assert.equal(JSON.stringify(cases),before);
console.log(`PASS: tag limits, normalization, escaping, ${cases.length} legacy cases, edit preservation/removal, new identity, final CTA placement and unchanged article/SEO.`);
